# Generated by Django 4.0.4 on 2022-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('genre', models.CharField(choices=[('Adventure', 'Adventure'), ('Literary Fiction', 'Literary Fiction'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Drama', 'Drama'), ('Comedy', 'Comedy')], max_length=100)),
                ('quantity_of_page', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
